### A simple function to perform gauss elimination on matrices

Author: Vignesh Sathyaseelan (vsathyas@purdue.edu)

In [1]:
import numpy as np

In [2]:
def gauss_elim(A,b):
    n = len(A) 
    
    #Elimination 
    for i in range(n-1): 
        for j in range(i+1,n):
            if A[j,j]:
                factor = A[j,i]/A[i,i]

            for k in range(n):               
                A[j,k] = A[j,k] - (factor * A[i,k])

            b[j] = b[j] - (factor * b[i])
    
    #initialze solution vector 
    x=np.zeros(n) 

    #Back substitution
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(n-1, i, -1):
            tmp -= x[j]*A[i,j]
        x[i] = tmp/A[i,i]

    return A,x

In [3]:
#Driver Code

#A = nxn matrix
A = np.array([[-23.0, 26.0, -42.0, -32.0, -90.0],[-2.0, 3.0, 0.0, -3.0, -4.0],\
              [-17.0, 19.0, -28.0, -22.0, -63.0],[-13.0,14.0,-24.0,-16.0,-52.0],\
              [18.0,-20.0,-32.0,23.0,69.0]])  

#b = nx1 vector 
b = np.array([-6.0,-2.0,-3.0,-2.0,3.0]) 

#Function Call
R,x = gauss_elim(A,b) 

#Print Output
print(f'After Gauss Elemination, R = \n {np.round(R,3)} \n')
print(f'solution (x) = \n {np.round(x,3)} \n') 

After Gauss Elemination, R = 
 [[-23.     26.    -42.    -32.    -90.   ]
 [  0.      0.739   3.652  -0.217   3.826]
 [  0.      0.      4.118   1.588   4.647]
 [ -0.      0.      0.      0.657  -1.114]
 [  0.      0.      0.      0.    112.174]] 

solution (x) = 
 [-5.279 -4.198  0.012 -0.523  0.384] 

