### 3. EignenValues - Power Method 
 Autor: Vignesh Sathyaseelan (vsathyas@purdue.edu)

In some problems, we only need to find the largest dominant eigenvalue and its corresponding eigenvector. In this case, we can use the power method - a iterative method that will converge to the largest eigenvalue. Let’s see the following how the power method works.

$$ AU_{k} = \lambda _{k} U_{k} $$

Where;

1) The A is the matrix. 

2) The $u_{k-1}$ is the eigenvector.

3) The $u_{1}$ is the inital guess eigenvector.

4) $\lambda _{k}$ is the correcspoding eigenvalue

Using $A^{-1}$ give you the lowest eigenvalue

In [1]:
import numpy as np

In [2]:
def scale(x):
    scale_f = np.max(x)
    x_scale = np.round(x/ scale_f,2)
    return x_scale, np.round(scale_f,2)

def power_it(A,eig_vec,n_iter=25):  
    for i in range(n_iter):
        eig_vec,eig_val = scale(np.dot(A,eig_vec))
    return eig_vec,eig_val

In [3]:
#Driver Code

A = np.array([[2,-12],[1,-5]])
x  = np.ones(len(A))
print('Matrix A = \n {}'.format(A))
print('eigen vector = {} eigen value = {} \n'.format(*power_it(A,x)))

A = np.array([[1,2,0],[-2,1,2],[1,3,1]])
x  = np.ones(len(A))
print('Matrix A = \n {}'.format(A))
print('eigen vector = {} eigen value = {} \n'.format(*power_it(A,x)))

Matrix A = 
 [[  2 -12]
 [  1  -5]]
eigen vector = [3. 1.] eigen value = -2.0 

Matrix A = 
 [[ 1  2  0]
 [-2  1  2]
 [ 1  3  1]]
eigen vector = [0.5 0.5 1. ] eigen value = 3.0 

